### ISSUE TITLE
the SCARED datase

### ISSUE THREAD

**Issue by songzheng112009** [BeileiCui/EndoDAC#1]
Could you please send me the SCARED dataset. I tried to send the challenge rule to Allen, but there is no response. My email is 1120099373sz@gmail.com. Thank you!

**Comment by BeileiCui** [comment]
Hi, actually the SCARED dataset is really large more than 200G so I currently don't have enough cloud space to share to you. Have the organizer of MICCAI 2019 challenge reply to you?

**Comment by songzheng112009** [comment]
Thank you for your reply. The official website has now replied to me
