### ISSUE TITLE
Issues running depth inference

### ISSUE THREAD

**Issue by charliebudd** [BeileiCui/EndoDAC#3]
I'm trying to run your tuned model on some images. However, I'm noticing the inference seems quite poor. More over, there is some variation in the output each time the model is loaded. This suggests to me that some weights are being left uninitialised. I noticed that strict checking is disabled when the depth anything weights are loaded....
https://github.com/BeileiCui/EndoDAC/blob/d36b36d74846a9978f13c0c3baeb2ead267b0c69/models/endodac/endodac.py#L191

Enabling this gives alot of missing and unexpected keys, I was wondering if all of these are expected errors? It's possible that there is a versioning issue giving different key names, allthough I'm using the requirements file in this repo to install dependencies. 

> RuntimeError: Error(s) in loading state_dict for endodac:
        Missing key(s) in state_dict: "encoder.blocks.2.residual_.conv1.weight", "encoder.blocks.2.residual_.norm1.weight", "encoder.blocks.2.residual_.norm1.bias", "encoder.blocks.2.residual_.conv2.weight", "encoder.blocks.2.residual_.norm2.weight", "encoder.blocks.2.residual_.norm2.bias", "encoder.blocks.2.residual_.conv3.weight", "encoder.blocks.2.residual_.norm3.weight", "encoder.blocks.2.residual_.norm3.bias", "encoder.blocks.5.residual_.conv1.weight", "encoder.blocks.5.residual_.norm1.weight", "encoder.blocks.5.residual_.norm1.bias", "encoder.blocks.5.residual_.conv2.weight", "encoder.blocks.5.residual_.norm2.weight", "encoder.blocks.5.residual_.norm2.bias", "encoder.blocks.5.residual_.conv3.weight", "encoder.blocks.5.residual_.norm3.weight", "encoder.blocks.5.residual_.norm3.bias", "encoder.blocks.8.residual_.conv1.weight", "encoder.blocks.8.residual_.norm1.weight", "encoder.blocks.8.residual_.norm1.bias", "encoder.blocks.8.residual_.conv2.weight", "encoder.blocks.8.residual_.norm2.weight", "encoder.blocks.8.residual_.norm2.bias", "encoder.blocks.8.residual_.conv3.weight", "encoder.blocks.8.residual_.norm3.weight", "encoder.blocks.8.residual_.norm3.bias", "encoder.blocks.11.residual_.conv1.weight", "encoder.blocks.11.residual_.norm1.weight", "encoder.blocks.11.residual_.norm1.bias", "encoder.blocks.11.residual_.conv2.weight", "encoder.blocks.11.residual_.norm2.weight", "encoder.blocks.11.residual_.norm2.bias", "encoder.blocks.11.residual_.conv3.weight", "encoder.blocks.11.residual_.norm3.weight", "encoder.blocks.11.residual_.norm3.bias", "depth_head.conv_depth_1.head.0.weight", "depth_head.conv_depth_1.head.0.bias", "depth_head.conv_depth_1.head.2.weight", "depth_head.conv_depth_1.head.2.bias", "depth_head.conv_depth_1.head.4.weight", "depth_head.conv_depth_1.head.4.bias", "depth_head.conv_depth_2.head.0.weight", "depth_head.conv_depth_2.head.0.bias", "depth_head.conv_depth_2.head.2.weight", "depth_head.conv_depth_2.head.2.bias", "depth_head.conv_depth_2.head.4.weight", "depth_head.conv_depth_2.head.4.bias", "depth_head.conv_depth_3.head.0.weight", "depth_head.conv_depth_3.head.0.bias", "depth_head.conv_depth_3.head.2.weight", "depth_head.conv_depth_3.head.2.bias", "depth_head.conv_depth_3.head.4.weight", "depth_head.conv_depth_3.head.4.bias", "depth_head.conv_depth_4.head.0.weight", "depth_head.conv_depth_4.head.0.bias", "depth_head.conv_depth_4.head.2.weight", "depth_head.conv_depth_4.head.2.bias", "depth_head.conv_depth_4.head.4.weight", "depth_head.conv_depth_4.head.4.bias". 
        Unexpected key(s) in state_dict: "depth_head.scratch.output_conv1.weight", "depth_head.scratch.output_conv1.bias", "depth_head.scratch.output_conv2.0.weight", "depth_head.scratch.output_conv2.0.bias", "depth_head.scratch.output_conv2.2.weight", "depth_head.scratch.output_conv2.2.bias".

**Comment by BeileiCui** [comment]
Actually if you only want to test our checkpoint on some images and not want to train it, you don't have to download the Depth-Anything pre-trained weight and only download the [checkpoint](https://drive.google.com/file/d/1qzAYBtwYJDN7hEi6pApqBOOz6pUhyY70/view?usp=drive_link).

**Comment by charliebudd** [comment]
Thanks for the response. I did some further debugging and tracked the issue down to my own code
