### ISSUE TITLE
The different  accuracy

### ISSUE THREAD

**Issue by suxuanya** [BeileiCui/EndoDAC#8]
Hello, I according to the method of segmentation of https://github.com/ShuweiShao/AF-SfMLearner data set. In order to extract simple left view, I modified the/root/EndoDAC/datasets/scared_dataset py code. As shown in the figure below:
![image](https://github.com/user-attachments/assets/71122c19-574a-4124-8f87-c50b6b00938b)
But I loaded checkpoints on [google driver](https://drive.google.com/file/d/1qzAYBtwYJDN7hEi6pApqBOOz6pUhyY70/view?usp=drive_link) and ran CUDA_VISIBLE_DEVICES=0 python evaluate_depth.py --data_path <your_data_path> \
- load_weights_folder '/ logs/endodac/models/weights_19' - eval_mono code after received is different from in the paper the accuracy of the excuse me why is this so?
<img width="1197" alt="4984329ddbef4e7998ea1495faffa51" src="https://github.com/user-attachments/assets/f955b4ea-d456-40d3-9f38-e07f556d51e1">

**Comment by BeileiCui** [comment]
Hi I checked again, I may have uploaded a different checkpoint from the one I mentioned in the paper. Anyway, this one is a little better than the one in the paper.
