### ISSUE TITLE
Pose-Intrinsics Net

### ISSUE THREAD

**Issue by VincentItaliano** [BeileiCui/EndoDAC#9]
In the paper you say that the Pose-Intrinsics Net estimates the motion variation between adjacent images. By default we load 3 frames for each training image: the previous frame, the current frame, and the next frame. But in the code we only estimate the motion between the current and the next frame, but not between the previous frame and the current frame.

For exemple in file ```trainer_end_to_end.py```, line 451 : 
```python 
for f_i in self.opt.frame_ids[1:]:
```
Do I need to modify this or have I misunderstood something?

**Comment by BeileiCui** [comment]
Hi, I think you misunderstood the code, The frame_ids is set to [0, -1,1] by default, so the inputs `inputs_all = [pose_feats[f_i], pose_feats[0]]` takes [0, -1] and [0, 1] by the `for` code, which means [current, previous] and [current next].

**Comment by VincentItaliano** [comment]
Hi, thank you for your reply. Indeed, I misread and was convinced I had read  [-1, 0, 1] instead of [0, -1, 1] ...
